### ISSUE TITLE
Leeres Statement

### ISSUE THREAD

**Issue by bafto** [bafto/DDP#13]
In DDP haben wir aktuell kein Statement, das nichts tut. In anderen Sprachen kann man einfach Semikolons oder z.B. leere Blöcke haben.
Prinzipiell ist das kein Problem, aber es führt manchmal zu etwas hässlichem Code, was wir natürlich vermeiden wollen.
Hier ein Beispiel aus examples/Rechner/TokenLeser.ddp:
```ddp
		Wenn Schlüsselwörter symbol enthält, füge symbol an symbole an.
		Wenn aber b eine Zahl ist, dann:
			Solange i kleiner als die Länge von ausdruck ist und
			(ausdruck an der Stelle (i plus 1)) eine Zahl ist, mache:
				Erhöhe i um 1.
				Füge (ausdruck an der Stelle i) an symbol an.
			Füge symbol an symbole an.
		Wenn aber b ein leeres Zeichen ist, mach weiter.
		Sonst:
			Schreibe ("Unzulässiges Symbol: " verkettet mit symbol) auf eine Zeile.
```

In Zeile 8 musste diese Hilfsfunktion benutzt werden:

```ddp
Die Funktion MachWeiter gibt nichts zurück, macht:
Und kann so benutzt werden:
	"mach weiter"
```
Ohne diese Hilfsfunktion hätte man `, dann:` und dann einen leeren Block geschrieben, was natürlich auf Deutsch wenig Sinn macht.

Deshalb schlage ich vor ein leeres Statement einzuführen, gerade für solche Platzhalter, das einfach nichts tut.
Syntaxvorschläge:
`tue nichts`, `mache nichts`, etc.

**Comment by NotLe0n** [comment]
Es sollte möglich sein, dass man jeden Code so refactoren kann um ohne leere Statements auskommen zu können.
Zum Beispiel:
```
		Wenn Schlüsselwörter symbol enthält, füge symbol an symbole an.
		Wenn aber b eine Zahl ist, dann:
			Solange i kleiner als die Länge von ausdruck ist und
			(ausdruck an der Stelle (i plus 1)) eine Zahl ist, mache:
				Erhöhe i um 1.
				Füge (ausdruck an der Stelle i) an symbol an.
			Füge symbol an symbole an.
		Sonst:
                        Wenn nicht b ein leeres Zeichen ist, dann:
			        Schreibe ("Unzulässiges Symbol: " verkettet mit symbol) auf eine Zeile.
```
(Natürlich sind negierungen noch etwas hässlich, aber anderes Problem.)

Ich finde es unnötig extra ein neues keyword einzuführen, das nichts tut.

**Comment by bafto** [comment]
> Es sollte möglich sein, dass man jeden Code so refactoren kann um ohne leere Statements auskommen zu können. Zum Beispiel:
> 
> ```
> 		Wenn Schlüsselwörter symbol enthält, füge symbol an symbole an.
> 		Wenn aber b eine Zahl ist, dann:
> 			Solange i kleiner als die Länge von ausdruck ist und
> 			(ausdruck an der Stelle (i plus 1)) eine Zahl ist, mache:
> 				Erhöhe i um 1.
> 				Füge (ausdruck an der Stelle i) an symbol an.
> 			Füge symbol an symbole an.
> 		Sonst:
>                         Wenn nicht b ein leeres Zeichen ist, dann:
> 			        Schreibe ("Unzulässiges Symbol: " verkettet mit symbol) auf eine Zeile.
> ```
> 
> (Natürlich sind negierungen noch etwas hässlich, aber anderes Problem.)
> 
> Ich finde es unnötig extra ein neues keyword einzuführen, das nichts tut.

So unnötig finde ich das gar nicht.
In diesem Beispiel kann man die Branch natürlich entsprechend umschreiben, aber es kommt durchaus vor (zwar nicht so oft, aber oft genug), dass man Code wie diesen sieht:
```
while( doStuffWithSideeffectUntilCondition() ) {};
```
Und obwohl das nicht so oft vorkommt und man es vielleicht anders schreiben könnte, würde ich solchen Code in DDP doch ermöglichen wollen, ohne sich eine eigene Funktion schreiben zu müssen.

Ein leeres Statement ( ; {} ) gibt es in den meisten anderen ("richtigen") Sprachen schließlich auch.

**Comment by NotLe0n** [comment]
Ich hatte die Idee vielleicht den Ellipsis Object (...) von Python zu klauen. Der Usecase wäre für Beispiele oder ToDos, wo wir momentan Kommentare für benutzen. 

Also:
```
Die Funktion foo, gibt eine Zahl zurück, macht:
    ...
Und kann so benutzt werden:
    "fooo"
```

Man könnte, dann statt einen Krypischen Error von wegen: "eine Funktion mit einen Rückgabetyp muss einen Wert zurückgeben" sagen: "Dieser Funktion fehlt eine Definition"

**Comment by bafto** [comment]
fixed in #80
