### ISSUE TITLE
Duden/Dateisystem

### ISSUE THREAD

**Issue by bafto** [bafto/DDP#14]
Ein Modul für den Duden um mit dem Dateisystem zu interagieren.

Features:
- [x] Schreiben von Dateien
- [x] Lesen von Dateien
- [x] Löschen von Dateien
- [x] Kopieren von Dateien
- [x] Verschieben von Dateien
- [x] Umbenennen von Dateien
- [x] Informationen über Dateien erhalten (Cs stat)

**Comment by NotLe0n** [comment]
Geschlossen mit 8fabe48
