### ISSUE TITLE
von ... bis ... mit nur einem Index

### ISSUE THREAD

**Issue by bafto** [bafto/DDP#16]
Syntax:
```ddp
Der Text t ist "Hallo Welt".
t bis 5. [ -> "Hallo"]
t ab 7. [ -> "Welt"]

[enstpricht]
t von 1 bis 5.
t von 7 bis (die Länge von t).
```

Kann entweder im Duden implementiert werden, oder inbuilt.
Inbuilt wäre praktische, vor allem da wir für den Duden keine Generics haben.

**Comment by NotLe0n** [comment]
Ich wäre dafür, dass der Syntax kein verkürztes Deutsch hat.

Ich schlage das vor:
```
t bis zum 5. Element.
t ab dem 7. Element.
```
