### ISSUE TITLE
Referenzen

### ISSUE THREAD

**Issue by Wallcutter** [bafto/DDP#24]
Referenzen funktionieren nur mit Text Variablen, bei allen anderen Datentypen schmeißt der compiler einen Syntax Fehler.

Bsp.:
Syntax Fehler (1000) in ddp_test_reference.ddp (Z: 11, S: 92)

11 |  Die Funktion Referenz_test mit den Parametern param1, param2 und param3 vom Typ Text, Zahl Referenz und Text, gibt nichts zurück, macht:
   |                                                                                                                                                       ^^^^^^

Es wurde und erwartet aber Referenz gefunden.

**Comment by bafto** [comment]
Diese Funktionsdeklaration ist auch nicht syntaktisch korrekt.

Es müsste `Zahlen Referenz` anstatt `Zahl Referenz` heißen.
Der compiler erkennt `Zahl` als validen Typ und erwartet als nächstes das `und`.
Der Fehler ist ziemlich irreführend, da werde ich mal reinschauen.

Fehlermeldungen sind allgemein noch eines der größten Probleme des compilers.

Korrigiere es mal zu `Zahlen Referenz` und lass mich wissen ob es dann geht. Wenn ja schließe ich den Issue.

**Comment by Wallcutter** [comment]
Danke für die schnelle Hilfe. Mit dem Plural funktioniert es bei Zahl(en), Kommazahl(en) und Buchstabe(n). In der Bedienungsanleitung ist das beim Punkt Referenzen am besten Hinzuzufügen, oder ist das schon irgendwo zu finden und ich habe es übersehen?
Nebenbei nur als Info, der Spielplatz ist momentan offline.

**Comment by bafto** [comment]
In der Bedienungsanleitung habe ich das tatsächlich vergessen, werde es demnächst hinzufügen.

Korrigiere mich wenn ich falsch liege, aber ich habe das so gesehen als `der Parameter x ist eine Zahlen Referenz` also `Zahlen` passend zum unbestimmten Artikel `eine`.

Der Spielplatz ist aufgrund einer Sicherheitslücke offline. Wir haben es erstmal gepatchet, warten aber noch auf Überprüfung von kompetenteren Leuten. Vielleicht ist er Morgen wieder online, vielleicht erst in ein paar Tagen.
