### ISSUE TITLE
Ersetze Boolean mit Wahrheitswert

### ISSUE THREAD

**Issue by mvelten1710** [bafto/DDP#29]
Bei einem Blick in die Beispiele ist aufgefallen wie sehr `Boolean` als nicht deutsches Wort heraussticht.
Da die Sprache noch in einem so frühen Stadium ist, ist die Frage: Könnte `Boolean` mit `Wahrheitswert` ersetzt werden?
Insbesondere da `true` und `false` schon durch `wahr` und `falsch` ausgedrückt werden.

**Comment by NotLe0n** [comment]
Diesen Gedanken hatten wir auch schon früher, damals war der Gedanke, dass "Boolean" als Fachwort zu DDP passt und, dass Programmierer sich damit einfacher an DDP anpassen können.

Jedoch wurde uns diese Änderung schon mehrmals vorgeschlagen, also denke ich, dass es wohl Nachfrage dafür gibt.

Diese Änderung wäre auch nicht schwer zu implementieren und würde fast keine existierende Programme kaputt machen, da der erste Release nur ca. ein Monat alt ist.

**Comment by bafto** [comment]
Da Stimme ich zu.
Mir persönlich ist es egal, der Änderung steht von mir aus nichts im Weg.
