### ISSUE TITLE
Laufzeitfehler beim Einbinden von Dateien, in denen Listen definiert sind

### ISSUE THREAD

**Issue by Magi3r** [bafto/DDP#34]
## Die Umstände:
Ich habe eine Datei _Hilfsmittel.ddp_, in der einzig eine Liste wie folgt definiert wird:
```ddp
Die öffentliche Buchstaben Liste kleinesABC ist eine Liste, die aus 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z' besteht.
```
Diese Datei binde ich in eine andere ein. Es macht allerdings keinen Unterschied, ob ich `kleinesABC` überhaupt benutze oder nicht.

## Der Fehler:
Der Quellcode kompiliert ohne Fehler, aber das ausführen Produziert:
```
free(): double free detected in tcache 2
Aborted
```

**Comment by bafto** [comment]
Repariert in 3b649e5a1ba56050569a8a1bc537b0eef08a4468
Sollte in der nächsten Version vom Alpha Release sein.
Danke für den Bug-Report, ist schön zu sehen, dass Leute den Kompilierer wirklich benutzen und die Sprache ausprobieren <3
