### ISSUE TITLE
Fehlerbehandlung

### ISSUE THREAD

**Issue by bafto** [bafto/DDP#35]
DDP hat momentan noch kaum Fehlerbehandlung. Das, was richtiger Fehlerbehandlung am nächsten ist sind die eher spärlich verteilten Text Referenz Ausgabeparameter  in einigen Dateisystem Funktionen.

Andere Sprachen verwenden verschiedene Ansätze zur Fehlerbehandlung:

- Exceptions (Java, C++, C#, etc.): Meiner Meinung nach sehr schlecht, da es zu großen Sprüngen im Code und unerwarteten Crashes führen kann. Außerdem ist es eher grob, da es unpraktikabel ist jeden Funktionsaufruf in einen `try-catch` Block zu packen. Zudem sind Exceptions syntaktisch nicht sehr schön
- Erros-as-Values (Go, Rust, Scala, etc.): Vom Konzept her sehr gut, aber unglaublich schwer es syntaktisch gut in DDP umzusetzen. Man bräuchte entweder Sum-types und Pattern-matching oder Polymorphismus und Standardwerte (null/nil), was in DDP beides sehr hässlich würde.
- Globale Fehler Variable (C): Nicht der allerbeste, aber ein sehr solider Ansatz. Außerdem sehr leicht ohne neue Features in DDP umzusetzen.

Für DDP schlage ich den letzten Ansatz vor.
Es würde ein Duden Module "Fehler" eingeführt werden, welches eine globale Fehler Variable managen würde und allerlei Hilfs-Funktionen definiert.
Jede Funktion, die einen Fehler zurückgeben könnte würde dann dieses Fehler Module benutzen um Fehler zu signalisieren.
Nach einem Funktionsaufruf, der einen Fehler auslösen kann würde man einfach den globalen Fehlerwert überprüfen.

Beispiel:
```ddp
Binde "Duden/Fehler" ein.
Binde "Duden/Dateisystem" ein.

Lösche die Datei "test.txt".
Wenn es einen Fehler gab, Schreibe (den letzten Fehler) auf eine Zeile.

Erstelle die Datei "test.txt".
Wenn es keinen Fehler gab, schreibe "Erfolg!".
```

**Comment by NotLe0n** [comment]
In #46 hinzugefügt
