### ISSUE TITLE
Fehlende Dokumentation für Strukturen

### ISSUE THREAD

**Issue by Magi3r** [bafto/DDP#36]
Durch das VSCode-plugin habe ich entdeckt, dass es structs gibt und wie man sie erstellt. Allerdings führt im Wiki der Link zur Dokumentation davon zu einer nicht existenten Seite. Wie greife ich auf Werte daraus wieder zu?

**Comment by bafto** [comment]
Danke für die Meldung. Wir arbeiten gerade aktiv an der Bedienungsanleitung weil wir sie jetzt auf github-pages hosten und dabei haben sich die Links alle geändert und müssen angepasst werden.

Hier ist der Korrekte Link: https://ddp.le0n.dev/Bedienungsanleitung/de/Programmierung/Strukturen/

Der Artikel ist noch nicht komplett vollständig soweit ich weiß, müsste aber bald kommen.
Wenn die Links nicht funktionieren, einfach links durch den Index schauen, da müsste alles drin sein.
