### ISSUE TITLE
Struct-Listen

### ISSUE THREAD

**Issue by Magi3r** [bafto/DDP#37]
Es wäre praktisch, eigene Strukturen/Datentypen in Listen speichern zu können.

Steht wahrscheinlich im Zusammenhang mit #18 .

**Comment by bafto** [comment]
Das ist bereits möglich, steht bloß noch nicht in der Bedienungsanleitung.
Wenn du eine Struktur `Vektor` hast, einfach `Vektor Liste` als Datentyp angeben.
Allerdings sind dafür natürlich keine Überladungen in `Duden/Listen` vorhanden (weil es noch keine Generics gibt), also müsstest du dir sowas selber schreiben.

**Comment by bafto** [comment]
@Magi3r siehe https://ddp.le0n.dev/Bedienungsanleitung/de/Programmierung/Strukturen/#struktur-listen

**Comment by Magi3r** [comment]
Aber für das Anhängen von Elementen an die Liste müsste ich noch meine eigene library schreiben und einbinden, richtig?

**Comment by bafto** [comment]
Genau, das ist dann halt nicht so effizient wie die Eingebauten Listen Funktionen. Das kommt in den Duden sobald wir Generics haben (was ein recht großes Feature ist, dauert also noch ein bisschen).

Bis dahin muss du sowas machen:
```ddp
Wir nennen die Kombination aus
	der Zahl x mit Standardwert 0,
	der Zahl y mit Standardwert 0,
einen Vektor,
und erstellen sie so:
	"Alias <x>"

Die Funktion anfügen_zahl2 mit den Parametern liste und vek vom Typ Vektor Listen Referenz und Vektor, gibt nichts zurück, macht:
	Speichere liste verkettet mit vek in liste.
Und kann so benutzt werden:
	"Füge <vek> an <liste> an"
```

**Comment by Magi3r** [comment]
Ahh, die Syntax mit `verkettet mit` hatte ich nicht gesehen. Danke!
