### ISSUE TITLE
Unaussagekräftiger Fehler

### ISSUE THREAD

**Issue by Magi3r** [bafto/DDP#38]
Ich bekomme einen Fehler beim Kompilieren von [meinem Code](https://github.com/Magi3r/AoC-2023/blob/1d733378036835dee781e8090e57df151bd64f82/05a.ddp). Der Language Server wirft aber keine Meldungen, der Kompiler auch keine, mit denen ich weiterarbeiten kann.

Der Fehler:
Fehler beim Kompilieren: Fehlerhafter Quellcode im Modul '05a.ddp', Kompilierung abgebrochen

**Comment by Magi3r** [comment]
Der Ast von `kddp parse` sagt auch schon, dass er Fehlerhaft ist. Aber ich kann jetzt auf den ersten Blick nicht sagen, wo das Problem liegt.

**Comment by bafto** [comment]
Gefixet in [367729e](https://github.com/DDP-Projekt/Kompilierer/commit/367729ec8f2046c30fac909911faebdd52c7b212).
Der Typechecker hat beim auswerten von Funktionsparametern eine Variable nicht zurückgesetzt.
Der Fix ist dann im nächsten Release mit drin.

Bis dahin:

Dein Fehler war, dass du `Duden/Statistik` einbinden musst und es in der letzten Zeile `der kleinste Wert aus <liste>` nicht *von* heißen muss.

**Comment by bafto** [comment]
@Magi3r es ist jetzt ne neue Version von der VSCode Extension (v0.0.5) online. Darin ist jetzt auch der Language Server enthalten.
Wenn du dazu upgradest hast du zumindest die Fehlerberichte vom LS, auch wenn der Kompilierer noch nicht geupdated ist.
