### ISSUE TITLE
Strukturen

### ISSUE THREAD

**Issue by NotLe0n** [bafto/DDP#5]
# Strukturen

Strukturen sind Benutzerdefinierte Datentypen, die mehrere Variablen (Eigenschaften) zusammenfassen.
Anders wie in anderen Sprachen können DDP's Strukturen keine Funktionen besitzen, da die selbe Funktionalität mit herkömmlichen Funktionen erreicht werden kann.

## Deklarationssyntax
Stukturen kann man mit folgender Syntax deklarieren:
```html
Die Struktur <Strukturname> beschreibt:
   <Der | Die> <Datentyp> <Eingenschaftsname> 
   <!-- weitere in Aufzählungformat -->
und wird so erstellt:
   <Aliase>
```

## Strukturinstanziierung
Siehe den Kommentar von @bafto zu dem Thema für einen besseren Vorschlag.

## Eigenschaftszugriff
Mit dem `von` Schlüsselwort kann man auf die Eigenschaften einer Struktur zugreifen.
Die Syntax würde dann so aussehen: 
```html
<Eigenschaftsname> von <Variablenname>
```

## Ein Beispiel
```
Die Struktur Schüler beschreibt:
    Die Zahl Alter mit dem Standartwert 0,
    der Text Name mit dem Standartwert "" und
    der Boolean Schläft mit dem Standartwert falsch
und wird so erstellt:
   "ein Schüler namens <Name>" oder
   "eine Schülerin names <Name>

Die Schüler Struktur Leon ist ein Schüler namens "Leon".
Alter von Leon ist 19.

Schläft von Leon ist wahr.

Binde "Duden/Ausgabe" ein.
Schreibe (Alter von Leon).
```

<h6 align=right>2. Abänderung</h6>

**Comment by bafto** [comment]
# Strukturinstanzierung
Anstatt alle Strukturen auf die gleiche Weise zu instanzieren sollten Strukturen genauso wie Funktionen Aliase benötigen, die eine grammatikalisch und kontextuell korrekte instanzierung ermöglichen.

Im Gegensatz zu Funktionsaliasen müssen diese nicht alle Funktions-Eigenschaften als Parameter enthalten, da jeder Eigenschaft ein Standardwert zugewiesen wird.
Das ermöglicht praktische Syntax wie diese:

```ddp
Die Struktur Vektor beschreibt:
    Die Zahl x mit Standardwert 0 und
    die Zahl y mit Standardwert 0
und wird so erstellt:
    "ein Vektor mit x gleich <x> und y gleich <y>" oder
    "der Nullvektor"
    
Die Vektor Struktur vek1 ist ein Vektor mit x gleich 1 und y gleich 1.
Die Vektor Struktur nullvek ist der Nullvektor.
```

# Typnamen und Artikel

Wenn man Aliase ins Extrem treiben möchte, könnte man sogar jede Struktur ihre eigenen Artikel/Pronomen beschreiben lassen, sodass dies:

```ddp
Der Vektor vek ist der Nullvektor.
```

valide Syntax ist.
Das wäre aber ein Feature was eher eine Spielerei und nicht wirklich wichtig wäre.
Da DDP von Grund auf allerdings eine Witz-Sprache ist könnte man in der Zukunft dennoch darüber nachdenken.

**Comment by bafto** [comment]
# Bessere Syntax um das grammatikalische Geschlecht zu erkennen

In den obigen Vorschlägen mussten wir für korrekte Typnamen ein generisches Femininum einführen (der Zusatz "Struktur" nach dem Typnamen) weil man aus der Deklaration das grammatikalische Geschlecht der Struktur nicht erkennen konnte.

Darum hier ein neuer Vorschlag:
(Für Sachen in <> können noch Details besprochen werden)

```ddp
<Wir/Man> nennen <eine Struktur / die Kombination> aus
    der Zahl z mit Standardwert 1,
    dem Boolean b mit Standardwert falsch,
    dem Text t mit Standardwert ""
einen Vektor / ein Haus / eine Uhr, [anhand von einen/ein/eine kann man das gramm. Geschlecht unterscheiden]
und erstellen ihn/sie/es so:
    "der Nullvektor" oder
    "eine Uhr mit Start <z>" oder
    "ein Haus" oder
    "ein altes Haus mit Addresse <t>"
```

Mit dieser Syntax kann man das grammatikalische Geschlecht einfach unterscheiden und somit diese Syntax ermöglichen:

```ddp
Der Vektor vek ist der Nullvektor.
Das Haus h ist ein leeres Haus.
Die Uhr uhr ist eine Stoppuhr.
```

Das geht dann auch in Loops etc. mit z.B. Für jede/jeden/jedes

**Comment by bafto** [comment]
Implementiert und bereit für den nächsten (Alpha) Release.
Sollte für den Beta Release noch etwas mehr getestet werden, vor allem in richtigen Programmen.
