### ISSUE TITLE
Wahrheitswert Initialisierung in Kombinationen

### ISSUE THREAD

**Issue by bafto** [bafto/DDP#51]
Problem:
```ddp
Wir nennen die Kombination aus
	dem Wahrheitswert foo mit Standardwert falsch, [Fehler: Es wurde wenn erwartet aber ein gefunden (1000)]
ein Foo,
und erstellen sie so:
	"Alias <x>"
```

Mögliche Lösung: Diese Art von Wahrheitswert Initialisierung in Kombinationen verbieten (hässlich)

**Comment by NotLe0n** [comment]
Verbieten würde Sinn machen, denn ich sehe gerade kein Fall wann man den Standardwert abhänging von einer globalen Variable machen will, also zum Beispiel:
```
Die Zahl z ist 3.
Wir nennen die Kombination aus
	dem Wahrheitswert foo mit Standardwert falsch, wenn z gleich 3 ist,
ein Foo,
und erstellen sie so:
	"Alias <x>"
```

Es würde jedoch eine „Ausnahme” hinzufügen an die man denken muss und im Duden dokumentieren muss.

**Comment by bafto** [comment]
fixed by accident in f8626e26
