### ISSUE TITLE
Einzelne Funktionen einbinden

### ISSUE THREAD

**Issue by NotLe0n** [bafto/DDP#6]
# Motivation
Momentan ist es nur möglich eine gesamte Datei einzubinden. Das bedeutet das man bei größeren Dateien viel mehr Funktionen einbindet als man eigentlich braucht. Vor allem bei Funktionen die Überladungen für jeden Datentyp besitzen. All diese unnötigen Deklarationen machen dem Parser viel mehr Arbeit.

So wäre es nutzlich wenn man nur die Funktionen einbinden kann, die man wirklich braucht.

# Neuer Syntax
```html
Binde die Funktion <Funktionsname> aus "<Dateipfad>" ein.
```

Vielleicht ist es auch sinnvoll mehrere Funktionen gleichzeitig einbinden zu können, um zu verhindern auf mehrere Zeilen fast das gleiche Stehen zu haben. So könnte eine weitere Syntax so aussehen:
```html
Binde die Funktionen <Funktionsnamenaufzaehlung> aus "<Dateipfad>" ein.
```

<h6 align=right>1. Abänderung</h6>

**Comment by bafto** [comment]
implemented on branch modules and merged in b70501d23fc047ae3d644f1d89e08a4c1502d6fa
