### ISSUE TITLE
Ordnereinbindungen

### ISSUE THREAD

**Issue by NotLe0n** [bafto/DDP#81]
## Warum
Das man einen Ordner aus Modulen einbinden kann ermöglicht die Trennung von einem Modul in mehere Teilmodule. Zum Beispiel: HTTP in HTTP/Client und HTTP/Server.

## Beispiel
```
.
|- A
   |- B
       |- C.ddp
   |- D.ddp
   |- E.ddp
```

`Binde alle Module aus "Duden/A" ein.` würde die Module `D.ddp` und `E.ddp` einbinden.
`Binde alle Module rekursiv aus "Duden/A" ein.` würde `C.ddp`, `D.ddp` und `E.ddp` einbinden.

**Comment by bafto** [comment]
done in #98
