### ISSUE TITLE
Forward declarations

### ISSUE THREAD

**Issue by bafto** [bafto/DDP#85]
# Das Problem

DDP hat das Problem, dass eine Funktion definiert sein muss bevor man sie aufrufen kann, da ihre Aliase sonst nicht bekannt sind.
Das selbe Problem gibt es in C und C++:
```C
int foo() {
    // error bar undefined
    return bar();
}
int bar() {
    return 1;
}
```

Die einfachste Lösung ist, die Funktionen einfach andersherum zu definieren. Das Funktioniert aber nicht wenn sie sich gegenseitig aufrufen:
```C
int i = 10;
int foo() {
    // error bar undefined
    return i != 0 ? bar() : 1;
}

int bar() {
    i--;
    return foo();
}
```
In diesem Fall ist die Lösung eine forward-declaration:
```C
int bar();
int i = 10;
int foo() {
    return i != 0 ? bar() : 1;
}

int bar() {
    i--;
    return foo();
}
```

Das bräuchte es auch in DDP um solche Konstrukte möglich zu machen.

# Syntax Vorschlag
```ddp
Die öffentliche Funktion bar mit den Parametern a, b und c vom Typ Zahl, Kommazahl und Text Referenz wird eine Zahl zurück geben und die Aliase 
"bar <a> <b> <c>", "<a> bar <b> <c>" und "barbara <a> bar <b> <c>" besitzen.
```

Solche Deklarationen müssen mit der späteren Definition eins-zu-eins übereinstimmen, bis auf die Aliase.
Ich würde sagen es dürfen Aliase weggelassen werden, falls man in der forward-declaration nicht alle braucht.

Außerdem müssen alle Funktionen die man deklariert auch im selben Modul definiert werden.

**Comment by NotLe0n** [comment]
In #95 mit folgendem Syntax implementiert:

Deklaration:
```
Die Funktion foo mit dem Parameter a vom Typ Zahl, gibt eine Zahl zurück,
wird später definiert
und kann so benutzt werden:
	"foo <a>"
```
Definition:
```
Die Funktion foo macht:
	Wenn a gleich 0 ist, dann:
		Schreibe "foo fertig" auf eine Zeile.
		Gib 0 zurück.
	Gib baz (a minus 1) zurück.
```
