### ISSUE TITLE
Kann man ein Windows-Programm mit DDP schreiben?

### ISSUE THREAD

**Issue by marlester-dev** [bafto/DDP#91]
So ein echtes Programm mit Buttons und so.

**Comment by bafto** [comment]
Ja, natürlich! Du musst bloß vorher die WinAPI wrappen...

DDP hat (mehr oder weniger gute) C Kompatibilität (siehe https://ddp.le0n.dev/Bedienungsanleitung/de/Programmierung/Funktionen/Externe-Funktionen/ oder noch besser, den Quellcode der DDP stdlib).
Damit kannst du eine C-Gui library wrappen, oder gleich direkt die WinAPI.
Hier einige Resourcen: 
- https://learn.microsoft.com/de-de/windows/win32/apiindex/windows-api-list
- https://github.com/RahulSreedharan/Win32-GUI-Programming-in-C
- https://dev.to/iamutkarshyadav/introduction-to-windows-gui-programming-with-c-building-your-first-window-4265
- Oder die populäre C GUI library ImGui: https://github.com/ocornut/imgui

Das ist natürlich ein enormer Aufwand, und GUI Programmierung ist kein vorrangiges Ziel von DDP, darum wird es eine ganze Weile dauern bis wir es im Duden o.ä. supporten (wenn überhaupt jemals).

Wenn du eine DDP Bibliothek dafür schreiben möchtest, nur zu! Es ist allerdings ziemlich aufwändig und ich würde eher davon abraten, da DDP sich im Moment noch in einer Phase ständiger Veränderung befindet. Gerade der C-Interopt und allgemein jedes Feature von DDP kann sich jederzeit fundamental verändern, deshalb müsste man solche größeren Bibliotheken wahrscheinlich ständig updaten.

Wenn wir in der Beta (v0.x.y-beta) sind oder in Version v1.x.y lohnt es sich wahrscheinlich eher darüber nachzudenken.
